name: build-and-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        repository: madmann91/slang
        path: slang

    - name: Configure Slang
      run: >
        cmake
        -S ${{github.workspace}}/slang
        -B ${{github.workspace}}/slang/build
        -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
        -DBUILD_TESTING=ON

    - name: Build Slang
      run: cmake --build ${{github.workspace}}/slang/build --config ${{matrix.build-type}}

    - name: Test Slang
      working-directory: ${{github.workspace}}/slang/build
      run: ctest -C ${{matrix.build-type}} --output-on-failure
